disable-require = false
#swarm-resource = "DOCKER_RESOURCE_GPU"

[nvidia-container-cli]
#root = "/run/nvidia/driver"
path = "@clipath@"
environment = []
# TODO: add option to enable logging
debug = "/var/log/nvidia-container-runtime-hook.log"
ldcache = "@ldcachepath@"
load-kmods = true
#no-cgroups = false
#user = "root:video"
ldconfig = "@@glibcbin@/bin/ldconfig"
